on:
  push:
    tags:
    - '*'

jobs:
  publish-linux:
    name: Publish release (Linux)
    runs-on: ubuntu-latest
    steps:
    - name: Extract version from tag
      uses: olegtarasov/get-tag@v2.1
      id: get_version
      with:
        tagRegex: 'v(.*)'

    - name: Initialize Java
      uses: actions/setup-java@v1
      with:
        java-version: 16

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Initialize QEMU
      uses: docker/setup-qemu-action@v1

    - name: Initialize buildx
      uses: docker/setup-buildx-action@v1

    - name: Prepare Docker build
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: assembleLib --no-daemon
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ github.token }}

    - name: DockerHub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: DockerHub publish
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
        context: .
        push: true
        tags: |
          sandpolis/agent:latest
          sandpolis/agent:${{ steps.get_version.outputs.tag }}

    - name: Update DockerHub Readme
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: sandpolis/agent

    - name: Publish release
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: publish --no-daemon
      env:
        SIGNING_PGP_KEY: ${{ secrets.SIGNING_PGP_KEY }}
        SIGNING_PGP_PASSWORD: ${{ secrets.SIGNING_PGP_PASSWORD }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ github.token }}

  publish-windows:
    name: Publish release (Windows)
    runs-on: windows-latest
    steps:
    - name: Extract version from tag
      uses: olegtarasov/get-tag@v2.1
      id: get_version
      with:
        tagRegex: 'v(.*)'

    - name: Initialize Java
      uses: actions/setup-java@v1
      with:
        java-version: 16

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Prepare Docker build
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: assembleLib --no-daemon
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ github.token }}

    - name: DockerHub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: DockerHub publish
      run: |
        docker build -t sandpolis/agent:latest -t sandpolis/agent:${{ steps.get_version.outputs.tag }} .
        docker push sandpolis/agent --all-tags
